### ISSUE TITLE
Feedback for “State management in React apps”

### ISSUE THREAD

**Issue by milhamm** [nowy/issues.fe.engineer#3]
There is a typo 'forr' at [**Valtio**](https://www.fe.engineer/handbook/state-management#valtio) section.

Valtio is a minimalist state management library that uses proxies to create reactive state objects. It provides a simple API _**forr**_ creating and accessing state, making it ideal for small to medium-sized apps.

**Comment by nowy** [comment]
Thank you 🙌  Have fixed this in the latest release :)
